### ISSUE TITLE
Applying a text structure does not cause unsaved changes

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/RichTextEditing#129] opened 2020-06-29 12:29 UTC
## Description
Applying a text structure to a part of the text does not add the "unsaved changes" indicator to the editor.

## How to reproduce
1. Open a new SquidWord document
2. Enter some text
  - Note that the "unsaved changes" indicator appears
3. Save the document (Ctrl+s/`Save` button)
  - the indicator disappears
4. Select part of the text
5. Apply `heading 1` to the text structure
  - The indicator doesn't reappear, even though there are unsaved changes

## Expected behavior
After applying a text structure, there are unsaved changes in the document and the appropriate indicator appears

**Comment by oleschl** [comment] 2020-07-02 14:19
If we do this we probably should adapt undo/redo to influence structure changes

**Comment by sirkrypt0** [comment] 2020-07-03 16:26
I think this is related to #133 and #136 where you are unable to create new structures after loading/saving

**Comment by oleschl** [comment] 2020-07-03 17:04
> I think this is related to #133 and #136 where you are unable to create new structures after loading/saving

I think its not directly related. Here is the problem that a applying a structure is not understand as an edit/change. #133 ~~and #136~~ seem to be a caused by a conflict with saved document.

**Comment by oleschl** [comment] 2020-07-04 23:31
> I think this is related to #133 and #136 where you are unable to create new structures after loading/saving

This is definitely related to #136. See my comment there.

**Comment by frcroth** [comment] 2020-07-13 12:56
Should also be fixed with 4dd6472

**Closed as completed by frcroth** 2020-07-13 12:56 UTC
Labels: bug
